[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "metaMuseomics"
version = "0.0.1"
description = "A collection of Python modules and wrappers for use in historical metagenome assembly and analyses. Designed in mind for pipeline use, but can be used as customisable standalone tools."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "pandas",
    "pgzip",
    "seqpy-tools"
]

authors = [
    {name = "Maria Kamouyiaros"}
]

[project.urls]
Homepage = "https://github.com/museomics/metaMuseomics"
Repository = "https://github.com/museomics/metaMuseomics"
Issues = "https://github.com/museomics/metaMuseomics/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
metamuseomics = [
    "r_scripts/**/*.R",
]

[project.scripts]
mm-setup-library = "metamuseomics.setup_library_dir:main"
mm-fastqc = "metamuseomics.fastqc_wrapper:main"
mm-fastp = "metamuseomics.fastp_module:main"
mm-decontam = "metamuseomics.decontam_module:main"
mm-nonpareil = "metamuseomics.nonpareil_module:main"
mm-assembly = "metamuseomics.assembly_module:main"
mm-kraken2 = "metamuseomics.kraken2_wrapper:main"
mm-busco = "metamuseomics.busco_wrapper:main"
mm-cutadapt = "metamuseomics.cutadapt_module:main"
mm-ids2csv = "metamuseomics.ids2csv:main"
mm-binning = "metamuseomics.binning_module:main"
